/* src/icon/IconPin2.svelte generated by Svelte v3.46.2 */
import {
	SvelteComponent,
	append,
	attr,
	detach,
	init,
	insert,
	noop,
	safe_not_equal,
	svg_element
} from "../_snowpack/pkg/svelte/internal.js";

function create_fragment(ctx) {
	let svg;
	let path0;
	let path1;
	let path2;
	let path3;

	return {
		c() {
			svg = svg_element("svg");
			path0 = svg_element("path");
			path1 = svg_element("path");
			path2 = svg_element("path");
			path3 = svg_element("path");
			attr(path0, "d", "m127.59 320.771-93.197 93.196c-22.178 22.179-34.393 51.667-34.393 83.033v15h15c31.366 0 60.854-12.214 83.033-34.394l93.196-93.196z");
			attr(path1, "d", "m361.114 291.263 26.997-33.315-134.06-134.061-33.314 26.998z");
			attr(path2, "d", "m178.834 151.408c-15.293.151-30.565 2.223-45.379 6.231-30.182 8.166-57.884 24.23-80.111 46.459 0 0 254.557 254.558 254.557 254.558 22.229-22.228 38.294-49.93 46.459-80.112 4.008-14.814 6.08-30.086 6.231-45.378z");
			attr(path3, "d", "m299.868 0-10.606 10.606c-14.166 14.166-21.967 33-21.967 53.033s7.801 38.867 21.967 53.032l106.066 106.066c14.623 14.623 33.824 21.932 53.032 21.932 19.204 0 38.414-7.312 53.033-21.931l10.607-10.607z");
			attr(svg, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg, "height", "512");
			attr(svg, "viewBox", "0 0 512 512");
			attr(svg, "width", "512");
			attr(svg, "fill", "currentcolor");
		},
		m(target, anchor) {
			insert(target, svg, anchor);
			append(svg, path0);
			append(svg, path1);
			append(svg, path2);
			append(svg, path3);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(svg);
		}
	};
}

class IconPin2 extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default IconPin2;