/* src/icon/IconSun.svelte generated by Svelte v3.46.2 */
import {
	SvelteComponent,
	append,
	attr,
	detach,
	init,
	insert,
	noop,
	safe_not_equal,
	svg_element
} from "../_snowpack/pkg/svelte/internal.js";

function create_fragment(ctx) {
	let svg;
	let circle;
	let line0;
	let line1;
	let line2;
	let line3;
	let line4;
	let line5;
	let line6;
	let line7;

	return {
		c() {
			svg = svg_element("svg");
			circle = svg_element("circle");
			line0 = svg_element("line");
			line1 = svg_element("line");
			line2 = svg_element("line");
			line3 = svg_element("line");
			line4 = svg_element("line");
			line5 = svg_element("line");
			line6 = svg_element("line");
			line7 = svg_element("line");
			attr(circle, "cx", "12");
			attr(circle, "cy", "12");
			attr(circle, "r", "5");
			attr(line0, "x1", "12");
			attr(line0, "x2", "12");
			attr(line0, "y1", "1");
			attr(line0, "y2", "3");
			attr(line1, "x1", "12");
			attr(line1, "x2", "12");
			attr(line1, "y1", "21");
			attr(line1, "y2", "23");
			attr(line2, "x1", "4.22");
			attr(line2, "x2", "5.64");
			attr(line2, "y1", "4.22");
			attr(line2, "y2", "5.64");
			attr(line3, "x1", "18.36");
			attr(line3, "x2", "19.78");
			attr(line3, "y1", "18.36");
			attr(line3, "y2", "19.78");
			attr(line4, "x1", "1");
			attr(line4, "x2", "3");
			attr(line4, "y1", "12");
			attr(line4, "y2", "12");
			attr(line5, "x1", "21");
			attr(line5, "x2", "23");
			attr(line5, "y1", "12");
			attr(line5, "y2", "12");
			attr(line6, "x1", "4.22");
			attr(line6, "x2", "5.64");
			attr(line6, "y1", "19.78");
			attr(line6, "y2", "18.36");
			attr(line7, "x1", "18.36");
			attr(line7, "x2", "19.78");
			attr(line7, "y1", "5.64");
			attr(line7, "y2", "4.22");
			attr(svg, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg, "fill", "none");
			attr(svg, "stroke", "currentColor");
			attr(svg, "stroke-linecap", "round");
			attr(svg, "stroke-linejoin", "round");
			attr(svg, "stroke-width", "2");
			attr(svg, "viewBox", "0 0 24 24");
		},
		m(target, anchor) {
			insert(target, svg, anchor);
			append(svg, circle);
			append(svg, line0);
			append(svg, line1);
			append(svg, line2);
			append(svg, line3);
			append(svg, line4);
			append(svg, line5);
			append(svg, line6);
			append(svg, line7);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(svg);
		}
	};
}

class IconSun extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default IconSun;