/* src/icon/IconDiscord.svelte generated by Svelte v3.46.2 */
import {
	SvelteComponent,
	append,
	attr,
	detach,
	init,
	insert,
	noop,
	safe_not_equal,
	svg_element,
	text
} from "../_snowpack/pkg/svelte/internal.js";

function create_fragment(ctx) {
	let svg;
	let defs;
	let style;
	let t;
	let title;
	let g;
	let path0;
	let path1;
	let ellipse0;
	let ellipse1;
	let path2;
	let path3;

	return {
		c() {
			svg = svg_element("svg");
			defs = svg_element("defs");
			style = svg_element("style");
			t = text(".cls-1 {\n      fill: #010101;\n    }\n    ");
			title = svg_element("title");
			g = svg_element("g");
			path0 = svg_element("path");
			path1 = svg_element("path");
			ellipse0 = svg_element("ellipse");
			ellipse1 = svg_element("ellipse");
			path2 = svg_element("path");
			path3 = svg_element("path");
			attr(path0, "class", "cls-1");
			attr(path0, "d", "M10.55,25C9.3,25.63,5,23.38,3.82,22.29,3.5,20.6,6,10.32,7.71,8.61S13,6.9,13,6.9a1,1,0,0,0,0-2c-.18,0-4.44,0-6.71,2.29C4.43,9.06.56,21.87,2.29,23.61c.84.83,4.9,3.48,7.75,3.48a3.07,3.07,0,0,0,1.41-.3,1,1,0,0,0,.44-1.34A1,1,0,0,0,10.55,25Z");
			attr(path1, "class", "cls-1");
			attr(path1, "d", "M25.71,7.19C23.44,4.93,19.18,4.9,19,4.9a1,1,0,0,0,0,2c1,0,3.89.31,5.29,1.71,1.71,1.71,4.21,12,3.89,13.68C27,23.38,22.7,25.63,21.45,25a1,1,0,0,0-1.34.45,1,1,0,0,0,.44,1.34,3.07,3.07,0,0,0,1.41.3c2.85,0,6.91-2.65,7.75-3.48C31.44,21.87,27.57,9.06,25.71,7.19Z");
			attr(ellipse0, "class", "cls-1");
			attr(ellipse0, "cx", "12");
			attr(ellipse0, "cy", "17.4");
			attr(ellipse0, "rx", "2");
			attr(ellipse0, "ry", "2.25");
			attr(ellipse1, "class", "cls-1");
			attr(ellipse1, "cx", "20");
			attr(ellipse1, "cy", "17.4");
			attr(ellipse1, "rx", "2");
			attr(ellipse1, "ry", "2.25");
			attr(path2, "class", "cls-1");
			attr(path2, "d", "M24,11.9a1,1,0,0,0,.85-.47,1,1,0,0,0-.32-1.38c-8.43-5.27-16.71-.22-17.06,0a1,1,0,0,0,1.06,1.7c.3-.19,7.58-4.6,14.94,0A1,1,0,0,0,24,11.9Z");
			attr(path3, "class", "cls-1");
			attr(path3, "d", "M23.09,23.32a1.15,1.15,0,0,0,.2.29,1,1,0,0,0,1.42,0A4.11,4.11,0,0,0,26,20.9a1,1,0,0,0-.56-.9,1,1,0,0,0-1.05.11A12.9,12.9,0,0,1,16,23h0a13,13,0,0,1-8.37-2.9A1,1,0,0,0,6.56,20a1,1,0,0,0-.56.9,4.11,4.11,0,0,0,1.29,2.71,1,1,0,0,0,1.42,0,1.15,1.15,0,0,0,.2-.29A14.34,14.34,0,0,0,15.66,25h.68A14.34,14.34,0,0,0,23.09,23.32Z");
			attr(g, "id", "Discord");
			attr(svg, "viewBox", "0 0 32 32");
			attr(svg, "xmlns", "http://www.w3.org/2000/svg");
		},
		m(target, anchor) {
			insert(target, svg, anchor);
			append(svg, defs);
			append(defs, style);
			append(style, t);
			append(svg, title);
			append(svg, g);
			append(g, path0);
			append(g, path1);
			append(g, ellipse0);
			append(g, ellipse1);
			append(g, path2);
			append(g, path3);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(svg);
		}
	};
}

class IconDiscord extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default IconDiscord;