/* src/icon/IconDotsVerticle.svelte generated by Svelte v3.46.2 */
import {
	SvelteComponent,
	append,
	attr,
	detach,
	init,
	insert,
	noop,
	safe_not_equal,
	svg_element
} from "../_snowpack/pkg/svelte/internal.js";

function create_fragment(ctx) {
	let svg;
	let circle0;
	let circle1;
	let circle2;
	let circle3;
	let circle4;
	let circle5;

	return {
		c() {
			svg = svg_element("svg");
			circle0 = svg_element("circle");
			circle1 = svg_element("circle");
			circle2 = svg_element("circle");
			circle3 = svg_element("circle");
			circle4 = svg_element("circle");
			circle5 = svg_element("circle");
			attr(circle0, "cx", "8");
			attr(circle0, "cy", "12");
			attr(circle0, "r", "1");
			attr(circle1, "cx", "8");
			attr(circle1, "cy", "5");
			attr(circle1, "r", "1");
			attr(circle2, "cx", "8");
			attr(circle2, "cy", "19");
			attr(circle2, "r", "1");
			attr(circle3, "cx", "16");
			attr(circle3, "cy", "12");
			attr(circle3, "r", "1");
			attr(circle4, "cx", "16");
			attr(circle4, "cy", "5");
			attr(circle4, "r", "1");
			attr(circle5, "cx", "16");
			attr(circle5, "cy", "19");
			attr(circle5, "r", "1");
			attr(svg, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg, "viewBox", "0 0 24 24");
			attr(svg, "fill", "none");
			attr(svg, "stroke", "currentcolor");
			attr(svg, "stroke-width", "2");
			attr(svg, "stroke-linecap", "round");
			attr(svg, "stroke-linejoin", "round");
		},
		m(target, anchor) {
			insert(target, svg, anchor);
			append(svg, circle0);
			append(svg, circle1);
			append(svg, circle2);
			append(svg, circle3);
			append(svg, circle4);
			append(svg, circle5);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(svg);
		}
	};
}

class IconDotsVerticle extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default IconDotsVerticle;